/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package observerweatherpattern;

import java.text.DateFormat;
import java.text.DateFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Mickael Walter
 */
public class WeatherMain extends javax.swing.JFrame {
    
    //Global variables- for my date for each button...
        DateFormatSymbols symbols = new DateFormatSymbols();
        Date date = new Date();
        DateFormat full = new SimpleDateFormat("MMMM dd, yyyy");
        DateFormat time = new SimpleDateFormat("HH:mm");

    /**
     * Creates new form WeatherMain
     */
    public WeatherMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titlelbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoLBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        nameTXT = new javax.swing.JTextField();
        btnSubscribe = new javax.swing.JButton();
        btnMon = new javax.swing.JButton();
        btnTues = new javax.swing.JButton();
        btnWed = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        appIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weather Observer");
        setLocation(new java.awt.Point(120, 100));
        setResizable(false);

        Titlelbl.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Titlelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titlelbl.setText("Port-of-Spain Weather");

        logoLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/observerweatherpattern/TTWLogo.png"))); // NOI18N
        logoLBL.setMaximumSize(new java.awt.Dimension(300, 350));
        logoLBL.setMinimumSize(new java.awt.Dimension(300, 350));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter your name and subscribe");

        nameTXT.setBackground(new java.awt.Color(204, 204, 204));
        nameTXT.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        nameTXT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnSubscribe.setBackground(new java.awt.Color(255, 51, 51));
        btnSubscribe.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnSubscribe.setForeground(new java.awt.Color(51, 51, 51));
        btnSubscribe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/observerweatherpattern/bell.png"))); // NOI18N
        btnSubscribe.setText("Subscribe");
        btnSubscribe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubscribeActionPerformed(evt);
            }
        });

        btnMon.setBackground(new java.awt.Color(51, 51, 51));
        btnMon.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnMon.setForeground(new java.awt.Color(255, 51, 51));
        btnMon.setText("MONDAY");
        btnMon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMonMouseClicked(evt);
            }
        });

        btnTues.setBackground(new java.awt.Color(51, 51, 51));
        btnTues.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnTues.setForeground(new java.awt.Color(255, 51, 51));
        btnTues.setText("TUESDAY");
        btnTues.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTues.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTuesMouseClicked(evt);
            }
        });

        btnWed.setBackground(new java.awt.Color(51, 51, 51));
        btnWed.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnWed.setForeground(new java.awt.Color(255, 51, 51));
        btnWed.setText("WEDNESDAY");
        btnWed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWedMouseClicked(evt);
            }
        });

        lblInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/observerweatherpattern/information.png"))); // NOI18N
        lblInfo.setToolTipText("After clicking subscribe, click any day for weather update");
        lblInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(logoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMon)
                                .addGap(39, 39, 39)
                                .addComponent(btnTues))
                            .addComponent(nameTXT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnSubscribe))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnWed))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubscribe)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMon)
                    .addComponent(btnTues)
                    .addComponent(btnWed))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        appIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/observerweatherpattern/cloudy.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Titlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appIcon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubscribeActionPerformed
        Subscriber sub = new Subscriber();
        sub.setVisible(true);
        
        //Sets the title name to the name of the subscriber
        sub.setTitle(this.nameTXT.getText());
    }//GEN-LAST:event_btnSubscribeActionPerformed

    private void btnMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMonMouseClicked
        //Monday's weather logic
        Monday mon = new Monday();
        mon.setVisible(true);
        //Create Subject
        wTopic topic = new wTopic();
        
        wObserver a = new wTopicSubscriber(this.nameTXT.getText());
        topic.attach(a);
        a.setSubject(topic);
        
        mon.setTitle("Monday's weather as at " + full.format(date));
        mon.timeInfo.setText(time.format(date));
        mon.txtWeatherInfo.setText(topic.sendMessage(" \n 30% chance of rain 🌧 | 🌫 SSE 10 KM/h"));
    }//GEN-LAST:event_btnMonMouseClicked

    private void btnTuesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTuesMouseClicked
        //Tuesday's logic
        Tuesday tues = new Tuesday();
        tues.setVisible(true);
        
        wTopic topic = new wTopic();
        
        wObserver b = new wTopicSubscriber(this.nameTXT.getText());
        topic.attach(b);
        b.setSubject(topic);
        
        tues.setTitle("Tuesday's weather as at " + full.format(date));
        tues.timeInfo.setText(time.format(date));
        tues.txtWeatherInfo.setText(topic.sendMessage(" \n 25 degrees | ⛅ | 🌫  E 5 KM/h"));
        
    }//GEN-LAST:event_btnTuesMouseClicked

    private void btnWedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWedMouseClicked
        // Wednesday's weather logic
        Wednesday wedns = new Wednesday();
        wedns.setVisible(true);
        
        wTopic topic = new wTopic();
        wObserver c = new wTopicSubscriber(this.nameTXT.getText() );
        topic.attach(c);
        c.setSubject(topic);
        
        wedns.setTitle("Wednesday's weather as at " + full.format(date));
        wedns.timeInfo.setText(time.format(date));
        wedns.txtWeatherInfo.setText(topic.sendMessage(" Mostly cloudy ☁ ☁ | 🌫 NE 12 KM/h"));
        
    }//GEN-LAST:event_btnWedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titlelbl;
    private javax.swing.JLabel appIcon;
    private javax.swing.JButton btnMon;
    private javax.swing.JButton btnSubscribe;
    private javax.swing.JButton btnTues;
    private javax.swing.JButton btnWed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel logoLBL;
    private javax.swing.JTextField nameTXT;
    // End of variables declaration//GEN-END:variables
}
